# Generated by Django 5.2.3 on 2025-06-17 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('Username', models.CharField(max_length=15)),
                ('Password', models.CharField(verbose_name='password')),
                ('UserID', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='date')),
                ('Time', models.TimeField(verbose_name='time')),
                ('Room', models.IntegerField(verbose_name='room')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Public.credentials')),
            ],
        ),
    ]
