# Generated by Django 5.2.3 on 2025-06-22 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credentials',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='credentials',
            old_name='UserID',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='credentials',
            old_name='Username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='meetings',
            old_name='Room',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='meetings',
            old_name='UserID',
            new_name='userID',
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='Time',
        ),
        migrations.AddField(
            model_name='meetings',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 22, 8, 24, 35, 949633, tzinfo=datetime.timezone.utc), verbose_name='Date and Time'),
            preserve_default=False,
        ),
    ]
